# config\config.yaml
model:
  name: HuggingFaceH4/zephyr-7b-beta
  temperature: 0.7
  max_tokens:  512
  top_p: 0.95


platforms:
  - twitter
  - medium
  - youtube

output:
  save_dir: data/processed/
